import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/posts" passHref>
        <h4>Posts</h4>
      </Link>
      <Link href="/news" passHref>
        <h4>News</h4>
      </Link>
      <Link href="/users" passHref>
        <h4>User</h4>
      </Link>
    </div>
  )
}
